# Generated by Django 3.1.4 on 2021-08-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('discount', models.CharField(max_length=50, null=True)),
                ('image', models.URLField(max_length=500, null=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.rating')),
            ],
        ),
    ]
