# Generated by Django 3.1.4 on 2021-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_rating',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
