# Generated by Django 3.1.4 on 2021-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_global_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='global_rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
